### ISSUE TITLE
The test scores

### ISSUE THREAD

**Issue by tong8080** [poojahira/image-captioning-bottom-up-top-down#14] opened 2019-08-30 07:53 UTC
Hello I run the python eval.py with your Pretrained model, but the scores are bad.
![image](https://user-images.githubusercontent.com/25942626/64003159-40f94680-cb3e-11e9-8d0f-3bd1731c0cd5.png)

**Comment by poojahira** [comment] 2019-08-30 11:49
Hello, hard to tell what the problem is without looking at your code. In one of the earlier issues someone else posted scores, you can check that out. It seems like you are doing something wrong.

**Comment by tong8080** [comment] 2019-08-30 12:05
I just use `with torch.no_grad():`for eval.py，because the error `out of memory`. Is it effect the scores?

**Comment by poojahira** [comment] 2019-08-30 12:07
No that should not affect it. Which test set is this? Is it the Karpathy test split?

**Comment by tong8080** [comment] 2019-08-30 12:13
I don't know. I just follow the steps.

**Comment by tong8080** [comment] 2019-08-30 12:18
And I'm not use the MSCOCO test dataset

**Comment by tong8080** [comment] 2019-09-03 07:12
Yes I use the Karpathy test split

**Comment by tong8080** [comment] 2019-09-03 08:39
And I see that use the pretrained model to generate caption. The generated captions are very bad，even can`t follow the grammar.

**Comment by poojahira** [comment] 2019-09-03 12:23
There is no way I can tell you what's wrong without seeing your code. The captions I generated were fine and the scores reported are the ones I have put up in the readme. I'm closing this issue now.

**Closed as completed by poojahira** 2019-09-03 12:23 UTC

**Comment by tong8080** [comment] 2019-09-03 12:40
Sorry to disturb you. Thanks.



发自我的iPhone


------------------ Original ------------------
